language: node_js
node_js:
- '12'
branches:
  only:
  - hexo
cache:
  directories:
  - node_modules
before_install:
- openssl aes-256-cbc -K $encrypted_f217180e22ee_key -iv $encrypted_f217180e22ee_iv
  -in .travis/id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- eval $(ssh-agent)
- ssh-add ~/.ssh/id_rsa
- cp .travis/ssh_config ~/.ssh/config
- git config --global user.name JobbyM
- git config --global user.email songzhipengmune@gmail.com
install:
- npm install hexo-cli -g
- npm install
- npm install hexo-deployer-git --save
- npm install hexo-algolia@1.0.1 --save
- npm install hexo-generator-sitemap --save
script:
- hexo clean
- hexo g
- hexo d
- hexo algolia
