language: node_js
node_js:
  - "6"

branches:
  only:
    - hexo

# Travis-CI Caching
cache:
  directories:
    - node_modules

# S: Buid Lifecycle
before_install:
  # Decrypt the private key
  - openssl aes-256-cbc -K $encrypted_b3c3b32c2fbe_key -iv $encrypted_b3c3b32c2fbe_iv -in .travis/id_rsa.enc -out ~/.ssh/id_rsa -d
  # Set the permission of the key:
  - chmod 600 ~/.ssh/id_rsa
  # Start SSH agent
  - eval $(ssh-agent)
  # Add the private key to the system
  - ssh-add ~/.ssh/id_rsa
  # Copy SSH config
  - cp .travis/ssh_config ~/.ssh/config
  # Set Git config
  - git config --global user.name JobbyM
  - git config --global user.email songzhipengmune@gmail.com

install:
  - npm install hexo-cli -g
  - npm install
  - npm install hexo-deployer-git --save
  - npm install hexo-algolia@0.2.0 --save

script:
  - hexo clean
  - hexo g
  - hexo d
  - hexo algolia

# E: Build LifeCycle
